name: CodeStyle

on: [push, pull_request]
jobs:
    run:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                operating-system: [ubuntu-latest]
                php-versions: ['8.1', '8.2']
            fail-fast: false
        name: PHP ${{ matrix.php-versions }} @ ${{ matrix.operating-system }}
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Install PHP
              uses: shivammathur/setup-php@master
              with:
                  php-version: ${{ matrix.php-versions }}
                  tools: 'composer:v2'
                  extensions: pcov, mbstring, posix
            - name: Install dependencies
              run: composer update --prefer-dist --no-progress --no-suggest ${{ matrix.composer-options }}
            - name: Run the tests
              run: composer run cs
